# unix commands
alias b='bat'
alias dir='tree --noreport -aI ".git|node_modules"'
alias dirn='tree --noreport -a'
alias dir1='dir -L 1'
alias dir2='dir -L 2'
alias dir3='dir -L 3'
alias dir4='dir -L 4'
alias dirn1='dira -L 1'
alias dirn2='dira -L 2'
alias dirn3='dira -L 3'
alias dirn4='dira -L 4'
alias dut='du -hs'
alias hg='history | grep -B1'
alias l='ls -1'
alias la='ls -1A'
alias lt='l -1t'
alias lta='ls -1At'
alias ll='ls -lh'
alias lla='ls -lhA'
alias llt='ls -lht'
alias llta='ls -lhAt'
alias lc='ls -C'
alias lca='lc -A'
alias lct='lc -t'
alias lcta='lc -tA'
alias pingg='ping -c 3 github.com'
alias rm='rm -I'
alias sudo='sudo '
alias vi='nvim'
alias wcl='wc -l'
alias zgrep='zgrep --color=auto'

# SUSE commands
alias zy='zypper'
alias zin='zypper install'
alias znf='zypper info 2>/dev/null'
alias zse='zypper search 2>/dev/null'
alias zi='zin'
alias zf='znf'
alias zs='zse'

# Dev
alias co='code'
alias py='python'
alias npm='pnpm'
alias cc='clang -std=c17 -Wall -Wextra'

# git
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gau='git add --update'
alias gb='git branch'
alias gbl='git branch --list'
alias gcb='git checkout -b'
alias gcm='git commit --message'
alias gco='git checkout'
alias gdf='git diff'
alias gdfc='git diff --cached'
alias glg='git log --oneline'
alias glog='git log --abbrev-commit | fold -s | bat'
alias gst='git status --untracked-files'
alias goops='git commit --amend --no-edit'
alias gundo='reset --soft HEAD^'
