# unix commands
alias b='bat'
alias cp='cp -i'
alias dir='tree --noreport -aI ".git|node_modules"'
alias dirn='tree --noreport -a'
alias dir1='dir -L 1'
alias dir2='dir -L 2'
alias dir3='dir -L 3'
alias dir4='dir -L 4'
alias dirn1='dira -L 1'
alias dirn2='dira -L 2'
alias dirn3='dira -L 3'
alias dirn4='dira -L 4'
alias dut='du -hs'
alias hg='history | grep -B1 --'
alias l='ls -1'
alias la='ls -1A'
alias lt='l -1t'
alias lta='ls -1At'
alias ll='ls -lh'
alias lla='ls -lhA'
alias llt='ls -lht'
alias llta='ls -lhAt'
alias lc='ls -C'
alias lca='lc -A'
alias lct='lc -t'
alias lcta='lc -tA'
alias lsd='ls -d'
alias pingg='ping -c 3 github.com'
alias pps='ps -o pid,ppid,state,comm,user'
alias ppsu='ps -o "pid,ppid,state,comm,user" -u$USER'
alias ppse='ps -eo "pid,ppid,state,comm,user"'
alias rm='rm -I'
alias sudo='sudo '
alias tree='tree --dirsfirst'
alias vi='nvim'
alias wcl='wc -l'
alias zgrep='zgrep --color=auto'

# SUSE commands
alias zy='zypper'
alias zin='zypper install'
alias znf='zypper info'
alias zse='zypper search'
alias zi='zin'
alias zf='znf'
alias zs='zse'
unalias you 2> /dev/null

# Network
alias ifconfig='ip addr'
alias route='ip route'

# Dev
alias co='code'
alias py='python3'
alias cc='$CC -std=c17 -Wall -Wextra'
alias cxx='$CXX -std=c++20 -Wall -Wextra'
alias npm='pnpm'
alias ns='npm search'
alias nf='npm info'
alias c++filt='c++filt -t | sed -f $DEV/cpp/c++filt.sed'

# git
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gau='git add --update'
alias gb='git branch'
alias gbl='git branch --list'
alias gcb='git checkout -b'
alias gcm='git commit --message'
alias gco='git checkout'
alias gdf='git diff'
alias gdfc='git diff --cached'
alias glg='git log --oneline'
alias glog='git log --abbrev-commit | fold -s | bat'
alias gst='git status --untracked-files'
alias goops='git commit --amend --no-edit'
alias gundo='git reset --soft HEAD^'
